# Ignore false positive from Rails' ActionText and ActiveStorage
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false

# Devise manages these internally
User:
  columns:
    email:
      ColumnPresenceChecker:
        enabled: false
    reset_password_token:
      UniqueIndexChecker:
        enabled: false
