inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "vendor/**/*"

Rails/BulkChangeTable:
  Exclude:
    - "db/migrate/**"

Rails/ThreeStateBooleanColumn:
  Exclude:
    - "db/migrate/**"

Rails/SkipsModelValidations:
  Exclude:
    - "test/**/*"

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpecRails/InferredSpecType:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/UnknownEnv:
  Environments: ["development", "test", "staging", "production"]
