# Run: EDITOR="code --wait" rails credentials:edit
# Paste this content, then replace with real values where needed.

vapid:
  public_key: BLYger3zOrm7sWU9E3JzInLn5G8YiXmGzEGXENXHJeIxZwJDC6xdcYs6dxjFCcMFMwG8SBc9woFJGOyCYmpEl90
  private_key: Fb-NrBegIX_OUaN_y04Rr6Ka5nibvuDqIEZ28Utq6fA

# ios:
#   bundle_identifier: com.season-app.ios
#   key_id: YOUR_KEY_ID
#   team_id: YOUR_TEAM_ID
#   apns_key: |
#     -----BEGIN PRIVATE KEY-----
#     YOUR_APNS_KEY
#     -----END PRIVATE KEY-----
