# This file was generated by the `rails generate rspec:install` command.
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups
end

# Define factories inline
require "factory_bot"
FactoryBot.define do
  factory :user do
    sequence(:email) { |n| "user#{n}@example.com" }
    password { "password123" }
    first_name { "Test" }
    birthdate { Date.new(1995, 1, 15) }
    cycle_length { 28 }
    onboarding_step { 1 }
    last_period_start { Time.zone.today - 14 }

    trait :onboarded do
      after(:create) do |user|
        user.update!(
          first_name: "Jane",
          birthdate: Date.new(1995, 1, 15),
          cycle_length: 28,
          last_period_start: Time.zone.today - 14,
          onboarding_completed: true,
          onboarding_step: 11
        )
      end
    end
  end
end
