class RestoreFullCycleDayContentText < ActiveRecord::Migration[8.1]
  def up
    local = Class.new(ActiveRecord::Base) do
      self.table_name = "cycle_day_contents"
      self.inheritance_column = nil
    end

    full_text = {
      superpower: {
        1 => "Progesterone is at its lowest point, which makes physical and mental 'letting go' easier. Your body sheds the uterine lining – in the same way, you can also mentally release old burdens.",
        2 => "Estrogen drops sharply, leading to less outward activity but more inner clarity. Your brain processes experiences more slowly, but more deeply – a foundation for creative insights.",
        3 => "Since estrogen is low, your brain switches from rational analysis to emotional perception. The amygdala (emotional center) and hippocampus (memory processing) work more closely together – you sense things more clearly.",
        4 => "Low estrogen means less dopamine → you become calmer, but more sensitive to emotional signals. Your brain focuses more strongly on interpersonal nuances – you sense what others are feeling.",
        5 => "Your body slows down metabolism to save energy – you focus on the essentials. The prefrontal cortex (for decision-making) is relieved, automatically blocking out unimportant things.",
        6 => "The low estrogen level reduces external distractions, so your focus is more strongly turned inward. Your brain works more slowly, but more deeply – you recognize your own patterns and emotional processes more clearly. This allows you to question old ways of thinking, gain deeper insights, and reflect more consciously on what really does you good.",
        7 => "Low estrogen means less emotional distraction, so your logical thinking becomes clearer. Your brain is not in 'socializing mode', but processes information at a deeper level.",
        8 => "Estrogen acts as a natural energizer – it boosts your endurance, concentration, and motivation. Your metabolism speeds up, you're physically more capable, and you have more desire to do things.",
        9 => "Since your brain is particularly active now, new ideas come to you faster. The rising estrogen level increases communication between brain regions, amplifying creative inspiration.",
        10 => "In this phase, your body is particularly receptive to muscle building. Rising estrogen improves recovery, while testosterone provides more strength – perfect for more intense workouts.",
        11 => "Estrogen influences not only your mood, but also your demeanor. You feel more confident, more communicative, and attract others with your energy – a natural effect that is evolutionarily linked to preparing for ovulation.",
        12 => "The rising estrogen level stabilizes your mood and provides greater emotional resilience. As a result, you are more patient and can respond to challenges in a more relaxed way.",
        13 => "Since your prefrontal cortex (responsible for logical thinking) is more active, you can make decisions faster and more effectively. You are less uncertain and can recognize opportunities more clearly.",
        14 => "Rising estrogen makes you more open to change. You can adjust more easily to new situations and feel motivated to try new things.",
        15 => "Rising estrogen strengthens synaptic connections, allowing you to absorb and recall knowledge more easily. Your working memory is particularly active, you can remember details better and learn faster.",
        16 => "Due to the rise in testosterone, you feel more confident, while dopamine boosts your enthusiasm. You can carry others away with your energy, appear convincing, and communicate ideas clearly.",
        17 => "Estrogen improves emotional perception and language processing, so you communicate sensitively but still clearly. This allows you to skillfully defuse conflicts and put yourself in others' shoes.",
        18 => "Due to high estrogen levels, you appear more open and charismatic, which is evolutionarily linked to partner selection. This phase is ideal for strengthening relationships – both personal and professional.",
        19 => "Estrogen promotes rapid analytical thinking, while dopamine increases your mental flexibility. This allows you to find creative solutions for complex problems and recognize patterns faster.",
        20 => "Your brain is now particularly sensitive to facial expressions, gestures, and moods. You intuitively recognize what others are feeling, even if they don't express it.",
        21 => "High testosterone levels give you determination, while estrogen brings emotional clarity. This means you can sense exactly what you want and what steps are necessary to achieve it.",
        22 => "Progesterone stabilizes your nervous system and ensures you handle challenges with more composure. Your body is programmed to be more resilient during this phase.",
        23 => "Progesterone makes your brain switch to 'threat analysis', which means you notice small inconsistencies and details faster. Your analytical thinking is particularly pronounced in this phase.",
        24 => "Since your body is preparing for the upcoming menstruation, progesterone sends a biological signal for structuring and completing tasks. You feel less like getting distracted and complete things efficiently.",
        25 => "Falling estrogen makes you less impulsive, while progesterone provides more perseverance. You can stick to plans and routines particularly well in this phase.",
        26 => "Less estrogen means less emotional distraction, so you can focus on practical solutions. Your brain processes information more pragmatically and strategically.",
        27 => "As your body adjusts to rest and structure, you automatically become more direct in your communication. You have less patience for unnecessary discussions and formulate your thoughts more efficiently.",
        28 => "Progesterone sharpens your gut feeling, while less estrogen means you are not influenced by wishful thinking. You can more easily judge whom you can trust and who may not be honest.",
        29 => "This phase is evolutionarily designed to make you more resilient to stress. Your body is ready to act efficiently rather than react emotionally.",
        30 => "Falling estrogen means your need for harmony decreases. You now have less patience for compromises that don't serve you, and set boundaries more clearly.",
        31 => "Since your testosterone level is slightly elevated, you are particularly assertive in this phase. You defend your opinion and push yourself through with more determination.",
        32 => "Progesterone signals your body to prepare for the next phase. As a result, you feel more intensely what does you good – be it healthy nutrition, rest, or movement.",
        33 => "Progesterone stabilizes your reaction to stress hormones like cortisol. As a result, you respond more calmly to problems and can view situations more objectively.",
        34 => "Since progesterone increases your need for order, it's easier for you to set priorities and plan tasks efficiently.",
        35 => "This phase brings you into a natural reflection about your own needs. You feel more strongly connected to yourself and can question old thought patterns."
      },
      watch_out_for: {
        1 => "Instead of forcing yourself through demanding days, it's more beneficial to adjust your pace and give your body what it needs right now.",
        2 => "Hormonal fluctuations can make you more sensitive; instead of judging yourself for them, it helps to consciously observe these feelings and accept them with more self-compassion.",
        3 => "Your nervous system is more sensitive in this phase, so it's helpful to consciously protect yourself in stressful moments and not let everything get to you.",
        4 => "It's easy to criticize yourself or feel less capable during this phase, but your body is doing a lot – so it helps to treat yourself with more leniency and kindness.",
        5 => "In this phase you tend to be more introverted and need more rest, so too much social interaction can drain your energy faster and stress you out.",
        6 => "Complex, stressful tasks or heated discussions can feel more burdensome during this phase, which is why it makes sense to consciously moderate mental exertion.",
        7 => "Your body is in a natural phase of withdrawal and processing, which is why it's a good opportunity to re-evaluate your emotions, goals, and needs.",
        8 => "Your body is producing more estrogen again, which boosts your energy and motivation; make sure to actively use this phase without overextending yourself.",
        9 => "Your body recovers faster, which is why this is the perfect time for more intense workouts or new athletic challenges.",
        10 => "In this phase, it's easier to try new things, as your willingness to take risks and your sense of adventure increase.",
        11 => "Even if you're full of drive, you might take on too much and pay for it later in the cycle phases.",
        12 => "Now is the best time to have clarifying or strategic conversations, as you are more balanced and solution-oriented.",
        13 => "Since you are more active, you might neglect your sleep, but good sleep helps you use your energy sustainably.",
        14 => "This phase is the transition to ovulation, where you have your greatest radiance; now is the perfect time to prepare for your next steps.",
        15 => "Your energy level is high, but you could overextend yourself, as you are often euphoric and full of drive in this phase, without noticing that you are overstraining your capacities.",
        16 => "Even if you feel capable, too much pressure can have negative consequences, as your nervous system is in a peak phase due to the hormonal rise, but stress can still cause long-term exhaustion.",
        17 => "Your metabolism is working faster, so a balanced diet is particularly important to avoid cravings, energy swings, and nutrient deficiencies.",
        18 => "In this phase, you sometimes overlook small complaints because you feel so good, which can lead you to ignore warning signs such as dehydration, muscle tension, or headaches.",
        19 => "Because you are so open and communicative, others might take advantage by piling on additional tasks or emotionally claiming you.",
        20 => "You are more sociable, but need recovery time afterwards, as the next cycle phase (luteal phase) is more inward-focused and you will then need more withdrawal.",
        21 => "Mood can swing dramatically after ovulation, as estrogen levels drop rapidly and progesterone becomes more noticeable, which often leads to irritability or exhaustion.",
        22 => "Your progesterone level is rising while estrogen slowly drops, which can make you emotionally more sensitive and more easily irritated, especially in stressful or overwhelming situations.",
        23 => "Your progesterone level is rising while estrogen slowly drops, which can make you emotionally more sensitive and more easily irritated, especially in stressful or overwhelming situations.",
        24 => "You now have a strong urge to do everything tidily and flawlessly, which can lead you to get lost in details and put yourself under unnecessary pressure.",
        25 => "Progesterone can promote water retention and tension, which can manifest as a feeling of tightness in the breasts, head, or joints; gentle movement helps relieve these complaints.",
        26 => "The luteal phase often brings mood swings that feel real, but are hormonally caused; it helps to look at yourself with compassion and not take everything too seriously.",
        27 => "Your patience is lower, which is why you might react more irritably to arguments; it's important in this phase to be more conscious with your words to avoid unnecessary tension.",
        28 => "You feel less like small talk and superficial conversations, which is why it's helpful to focus on deeper, meaningful conversations or to consciously take time for yourself.",
        29 => "You now have a strong urge to do everything tidily and flawlessly, which can lead you to get lost in details and put yourself under unnecessary pressure.",
        30 => "Your body processes stimulants more slowly, which is why too much coffee can amplify restlessness and sleep problems, and alcohol can trigger more intense mood swings.",
        31 => "Your sleep quality can be affected by hormone fluctuations, which is why conscious sleep hygiene helps you sleep more restfully and minimize fatigue the next day.",
        32 => "Your body is working more intensively to prepare for menstruation, which costs more energy; without enough rest, this can lead to faster exhaustion.",
        33 => "Your focus is now more on completion and reflection rather than new beginnings, which is why it makes more sense to finish existing tasks rather than take on new challenges.",
        34 => "Cravings are hormonally caused, but too much sugar or processed foods can amplify your mood swings and cause energy drops.",
        35 => "In this phase, one tends to view oneself more critically, which can affect your self-esteem, even though it's only hormonally caused."
      },
      sport: {
        1 => "In the first few days, your energy level can be very low due to the drop in hormones (estrogen & progesterone), so you shouldn't force yourself into physical activity if you feel exhausted.",
        2 => "Your body is in a regeneration phase, and intense training can release additional stress hormones (cortisol) that amplify your exhaustion.",
        3 => "Stretching exercises or light mobility training can help release tension in the lower back and hips, which often arises from cramps.",
        4 => "Your body is still regenerating, and heavy lifting can place additional strain on your joints and muscles, as your muscle coordination may be slightly impaired in this phase.",
        5 => "Your estrogen level begins to rise again, leading to more energy; this is a good time to gently return to strength training or moderate cardio.",
        6 => "Light strength training with moderate resistance can help activate your muscles without overtaxing your body.",
        7 => "Since the follicular phase comes with a natural performance boost, you can slowly adjust your training intensity to get back into a stronger rhythm.",
        8 => "Light to moderate strength training is ideal now, as your muscles are becoming more capable again and you feel stronger.",
        9 => "Your cardiovascular system becomes more resilient, so you can now slowly integrate longer or more intense cardio sessions like jogging or cycling.",
        10 => "In this phase, you can use heavier weights or higher resistance, as your body recovers better and your muscles work more efficiently.",
        11 => "Your body is now more capable and can better handle longer cardio or HIIT (High-Intensity Interval Training) sessions.",
        12 => "Your mental clarity and physical resilience are high, which is why you can try out new workouts or sports without quickly feeling overwhelmed.",
        13 => "If you're aiming for personal bests, these days are optimal, as your body is especially resilient due to the high estrogen level.",
        14 => "Now is the perfect time for demanding training such as strength training with heavy weights, sprints, or long cardio sessions.",
        15 => "Now is the perfect time for heavy strength training, as your body can better handle high loads and build muscle faster.",
        16 => "High estrogen and testosterone levels improve your reaction speed, strength, and power. Your body can now better handle intense loads and recovers faster. Use this phase for sprint training, HIIT, or strength exercises with explosive movements to tap your full performance potential.",
        17 => "Due to the hormonally induced loosening of ligaments and tendons, the likelihood of sprains or overstretching increases, so you should warm up particularly well and perform controlled movements.",
        18 => "Since you are particularly focused in this phase, you can work specifically on your technique, posture, or endurance limits.",
        19 => "Your body can now lift the most weight and build muscle efficiently, which is why this is the perfect moment for maximum strength training.",
        20 => "Your body and mind are optimal for collaborative workouts, whether team sports, group classes, or training together with friends.",
        21 => "After ovulation, the progesterone rise begins, which slowly changes your energy level – adjust your training in time.",
        22 => "Your body needs more recovery, as progesterone raises your body temperature and slightly reduces your endurance performance.",
        23 => "Your body now stores more water in the muscles, which can make movements feel unusually 'heavy'. Work with medium weights and focus on technique.",
        24 => "Your body has less coordination strength in this phase, so stability exercises and targeted activation of the deep muscles are sensible.",
        25 => "Gentle yoga, stretching, or pilates can help reduce stress and prevent menstrual complaints.",
        26 => "Some days you'll feel capable, others require more rest – pay attention to your individual well-being.",
        27 => "Water retention and muscle tension can increase; gentle stretching can ease tension in the lower back or legs.",
        28 => "Your body burns more carbohydrates than fat in this phase, which can reduce your endurance performance – short, moderate sessions are now more effective.",
        29 => "Use a foam roller or gentle massage balls to release tension in the legs, lower back, or shoulders, as water retention can make the tissue tighter.",
        30 => "It's normal to feel weaker or more sluggish on some days – this phase is not meant for peak performance, but for adjusted movement.",
        31 => "Your tendons and joints are more sensitive, which is why you should minimize the risk of injury through controlled movements.",
        32 => "Swimming, walking, or light cycling can help boost your well-being without overloading you.",
        33 => "Your breathing can become shallower, which can lead to tension – slow, deep breaths support the oxygen supply to your muscles.",
        34 => "Progesterone makes you more sensitive to stress hormones, so make sure not to push yourself too hard or get frustrated when your energy level is low.",
        35 => "Your menstruation is imminent, so it makes sense to adjust your routines now and consciously use movement to support your regeneration."
      },
      nutrition: {
        1 => "Blood loss lowers your iron level, which can cause fatigue. Reach for spinach, lentils, beetroot, pumpkin seeds, or meat (beef, liver) and combine them with vitamin C-rich foods (citrus fruits, peppers) to improve iron absorption.",
        2 => "Dark chocolate (at least 85% cocoa), almonds, bananas, and avocados are rich in magnesium and help relieve muscle cramps.",
        3 => "Salmon, chia seeds, walnuts, and flaxseeds reduce menstrual cramps and help lower inflammation in the body.",
        4 => "Heavily processed foods and ready meals often contain a lot of sodium, which increases water retention and can promote bloating.",
        5 => "Spinach, kale, and broccoli contain iron, magnesium, and B vitamins that boost your energy and support hormonal balance.",
        6 => "Bananas, salmon, potatoes, and sunflower seeds contain vitamin B6, which promotes serotonin production and can reduce mood swings.",
        7 => "Pumpkin seeds, sesame, and almonds provide healthy fats and zinc, which regulates the hormonal balance and supports the skin during menstruation.",
        8 => "Your body produces new blood cells after menstruation. Good iron sources are beetroot, lentils, spinach, quinoa, and eggs. Combine them with vitamin C (e.g. oranges, peppers) for better absorption.",
        9 => "Berries, dark chocolate (at least 85% cocoa), and green tea protect cells from oxidative stress and promote radiant skin.",
        10 => "Avocados, olive oil, walnuts, and chia seeds support estrogen production and promote stable hormonal balance.",
        11 => "Parsley or dandelion tea help flush out excess water and support kidney function.",
        12 => "Sauerkraut, kefir, and kimchi promote healthy gut flora, which is important for hormone regulation and nutrient absorption.",
        13 => "Linseed oil, salmon, chia seeds, and walnuts support the nervous system and ensure optimal brain function.",
        14 => "Almonds, hazelnuts, wheat germ, and avocados help protect cell membranes and stabilize estrogen.",
        15 => "Eggs, fish, tofu, or yogurt help prevent muscle breakdown and maintain your performance.",
        16 => "Pumpkin seeds, chickpeas, oysters, and cashews support egg maturation and help prevent skin blemishes in this phase.",
        17 => "Potatoes, pistachios, bananas, and sunflower seeds help strengthen the nervous system and prevent cravings.",
        18 => "Sauerkraut, kimchi, kefir, and yogurt promote stable digestion and support the immune system.",
        19 => "Quinoa, sweet potatoes, and whole grain rice stabilize your blood sugar and prevent energy drops.",
        20 => "Avocados, hazelnuts, sunflower seeds, and wheat germ protect your skin from hormonal fluctuations.",
        21 => "Nuts, olive oil, and fatty fish help stabilize the hormonal balance and minimize PMS symptoms.",
        22 => "They contain lignans, which help balance hormone levels.",
        23 => "These plants can help stabilize progesterone and ease PMS symptoms. Do not take if you use hormonal contraception, as they can affect the cycle.",
        24 => "These gluten-free alternatives support the liver in processing excess hormones. Avoid too much millet if you have an underactive thyroid, as it contains goitrogens that can inhibit iodine absorption.",
        25 => "These help reduce inflammation and promote a stable gut flora. Not suitable for vegetarians or vegans – alternatives are algae broth or plant-based collagen boosters like rosehip powder.",
        26 => "These have a natural diuretic effect and help against a bloated feeling. Avoid fennel if you have an estrogen-sensitive condition (e.g. endometriosis), as fennel can have a slight estrogen-like effect.",
        27 => "They offer a healthy alternative to sugar and provide minerals like potassium & magnesium. Avoid them if you are prone to blood sugar fluctuations, as they can quickly raise insulin levels.",
        28 => "They help avoid cravings and provide valuable proteins. Not suitable if you have a sensitive digestion, as they can promote bloating – in this case, soak well beforehand or eat sprouted.",
        29 => "This tea helps excrete excess fluids. Don't drink if you are already taking diuretic medication or have low blood pressure, as nettle has a strong diuretic effect.",
        30 => "They contain polyphenols that reduce menstrual complaints. Avoid large amounts if you are sensitive to fructose, as they can cause digestive discomfort.",
        31 => "They help produce serotonin and have a calming effect on the nervous system. Avoid instant oatmeal, as it has a high glycemic index and raises blood sugar quickly.",
        32 => "They are easy to digest and help prevent cramps.",
        33 => "They contain tryptophan, which improves sleep quality. Avoid macadamia nuts if you have a sensitive stomach, as they are high in fat and can trigger gastrointestinal complaints in some people.",
        34 => "These herbs calm the nervous system and help against sleep problems. Do not take in combination with sedatives or sleeping pills, as they can amplify the effect.",
        35 => "This combination helps avoid cravings and gives you sustainable energy. Avoid too much cinnamon (especially Cassia cinnamon) if you have liver problems, as it contains coumarin in large amounts, which can strain the liver."
      },
      fertility: {
        1 => "Extremely unlikely, except with very short cycles.",
        2 => "Extremely unlikely, except with very short cycles.",
        3 => "Extremely unlikely, except with very short cycles.",
        4 => "Low, but possible with short cycles.",
        5 => "Low, but possible with short cycles.",
        6 => "Only relevant with short cycles, otherwise still very low.",
        7 => "Only relevant with short cycles, otherwise still very low.",
        8 => "High with short cycles, moderate with longer cycles.",
        9 => "High with short cycles, moderate with longer cycles.",
        10 => "High, especially with medium-length cycles of 26-28 days.",
        11 => "High, especially with medium-length cycles.",
        12 => "Maximum with cycles of 26-30 days, as ovulation is imminent or has occurred.",
        13 => "Maximum with cycles of 26-30 days.",
        14 => "Maximum with cycles of 26-30 days.",
        15 => "Maximum chance of pregnancy with a regular cycle.",
        16 => "Maximum chance of pregnancy with a regular cycle.",
        17 => "Only still possible if ovulation occurred later than expected or sperm were already present.",
        18 => "Only still possible if ovulation occurred later than expected.",
        19 => "Only still possible if ovulation occurred later than expected.",
        20 => "Only relevant with very long cycles or late ovulation.",
        21 => "Only relevant with very long cycles or late ovulation.",
        22 => "No new fertilization possible, only implantation of an already fertilized egg.",
        23 => "No new fertilization possible, only implantation of an already fertilized egg.",
        24 => "No new fertilization possible, only implantation of an already fertilized egg.",
        25 => "No new fertilization possible, only implantation of an already fertilized egg.",
        26 => "No more possibility for fertilization, except an already fertilized egg implants.",
        27 => "No more possibility for fertilization, except an already fertilized egg implants.",
        28 => "No more possibility for fertilization, except an already fertilized egg implants.",
        29 => "No more possibility for fertilization, except an already fertilized egg implants.",
        30 => "No more possibility for fertilization, except an already fertilized egg implants.",
        31 => "No more possibility for fertilization, except an already fertilized egg implants.",
        32 => "Except a fertilized egg successfully implants.",
        33 => "Except a fertilized egg successfully implants.",
        34 => "Except a fertilized egg successfully implants.",
        35 => "Except a fertilized egg successfully implants."
      }
    }

    # rubocop:disable Rails/SkipsModelValidations
    full_text.each do |card_type, days|
      days.each do |day, long|
        local.where(cycle_day: day, card_type: card_type.to_s).update_all(long_text: long)
      end
    end
    # rubocop:enable Rails/SkipsModelValidations
  end

  def down
    # Irreversible — restores correct long_text values
  end
end
