name: SeasonApp
options:
  bundleIdPrefix: com.season-app
  deploymentTarget:
    iOS: "16.0"
packages:
  HotwireNative:
    url: https://github.com/hotwired/hotwire-native-ios
    from: 1.0.0
targets:
  SeasonApp:
    type: application
    platform: iOS
    sources:
      - path: SeasonApp
        excludes:
          - "Season Test"
    resources:
      - path: SeasonApp/path-configuration.json
    dependencies:
      - package: HotwireNative
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.season-app.ios
      INFOPLIST_FILE: SeasonApp/Info.plist
      GENERATE_INFOPLIST_FILE: NO
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "59"
